# Generated by Django 4.2.6 on 2023-11-09 02:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inicio', '0002_categorial_tipococina'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pais', models.CharField(max_length=50)),
                ('Estado', models.CharField(max_length=50)),
                ('Direccion', models.CharField(max_length=200)),
                ('Promedio', models.DecimalField(decimal_places=3, default=0, max_digits=3)),
                ('Apertura', models.TimeField()),
                ('Cierre', models.TimeField()),
                ('Descripción', models.CharField(max_length=280)),
                ('CategoriaL', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.categorial')),
                ('Propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('TipoCocinaID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.tipococina')),
            ],
        ),
        migrations.CreateModel(
            name='Resena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateField()),
                ('Descripcion', models.CharField(max_length=280)),
                ('Puntuacion', models.IntegerField()),
                ('RestauranteID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.restaurante')),
                ('UsuarioID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FotosResena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ruta', models.CharField(max_length=70)),
                ('ResenaID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.resena')),
            ],
        ),
        migrations.CreateModel(
            name='FotosLugar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ruta', models.CharField(max_length=70)),
                ('RestauranteID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.restaurante')),
            ],
        ),
    ]
