# Generated by Django 4.2.6 on 2023-11-09 04:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inicio', '0003_restaurante_resena_fotosresena_fotoslugar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fotoslugar',
            name='Ruta',
        ),
        migrations.RemoveField(
            model_name='fotosresena',
            name='Ruta',
        ),
        migrations.AddField(
            model_name='fotoslugar',
            name='Imagen',
            field=models.ImageField(null=True, upload_to='uploads/lugar'),
        ),
        migrations.AddField(
            model_name='fotosresena',
            name='Imagen',
            field=models.ImageField(null=True, upload_to='uploads/resena'),
        ),
        migrations.AlterField(
            model_name='restaurante',
            name='Propietario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
