# Generated by Django 4.2.6 on 2023-11-20 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0004_remove_fotoslugar_ruta_remove_fotosresena_ruta_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurante',
            old_name='TipoCocinaID',
            new_name='TipoCocina',
        ),
    ]
