# Generated by Django 4.2.6 on 2023-11-20 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0007_alter_restaurante_categorial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotoslugar',
            name='Imagen',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/lugar'),
        ),
        migrations.AlterField(
            model_name='fotosresena',
            name='Imagen',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/resena'),
        ),
        migrations.AlterField(
            model_name='restaurante',
            name='CategoriaL',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inicio.categorial'),
        ),
        migrations.AlterField(
            model_name='restaurante',
            name='TipoCocina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inicio.tipococina'),
        ),
    ]
