# Generated by Django 4.2.6 on 2023-11-20 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0008_alter_fotoslugar_imagen_alter_fotosresena_imagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurante',
            name='Descripción',
            field=models.CharField(blank=True, max_length=280, null=True),
        ),
        migrations.AlterField(
            model_name='restaurante',
            name='Promedio',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=3),
        ),
    ]
