# Generated by Django 4.2.6 on 2023-11-20 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0009_alter_restaurante_descripción_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotoslugar',
            name='RestauranteID',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='inicio.restaurante'),
        ),
    ]
