# Generated by Django 4.2.6 on 2023-12-07 18:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inicio', '0012_alter_resena_puntuacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotousuario',
            name='UsuarioID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
